---
clone:
  - name: clone
    image: docker.io/woodpeckerci/plugin-git
    settings:
      skip_verify: true

when:
  - event: [push, pull_request]

steps:
  - name: lint-yaml
    image: docker.io/cytopia/yamllint:latest
    commands:
      - yamllint -c .yamllint ansible/

  - name: lint-ansible
    image: docker.io/pipelinecomponents/ansible-lint:latest
    environment:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_ROLES_PATH: ansible/roles
    commands:
      - pip install ansible-core>=2.17
      - ansible-lint --profile production ansible/

  # Molecule tests require privileged containers + Podman socket.
  # Run locally with: mise run test:role -- <role>
  # TODO: re-enable once Woodpecker trusted repo + DinD is configured
