---
name: Lint

"on":  # yamllint disable-line rule:truthy
  push:
    branches: ["*"]
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: yamllint -c .yamllint ansible/

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ansible-core ansible-lint
      - run: ansible-lint --profile production ansible/
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_ROLES_PATH: ansible/roles
